title: Transform Denver
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.75
  brandStrength: 0.625448
  lightness: 0.4311170917935669
  brandColors:
    - '#000000'
    - '#343c3e'
    - '#eff9fb'
    - '#748283'
    - '#71efee'
  rhythmicContrast: 0.2216215897351503
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Transform Denver
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.87069
layout_spectrum: 0.6738351
