name: Transform Denver
favicon: null
layout_spectrum: 0.88026
typography_spectrum: 0.87069
title: Transform Denver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#343c3e'
    - '#eff9fb'
    - '#748283'
    - '#71efee'
  brandStrength: 0.1875
  lightness: 0.43111709179356694
  saturation: 0.75
  rhythmicContrast: 0.22162158973515034
purpose: []
